### ISSUE TITLE
Matlab version

### ISSUE THREAD

**Issue by brankaleon** [danielrherber/optimal-control-direct-method-examples#2]
Working Matlab version should be pointed out.
As an example it seems not working on R2015b

**Comment by danielrherber** [comment]
Hello brankaleon; thank you for pointing out this issue. Can you provide any additional information to help me fix this issue? Did you run the install script ([INSTALL_Direct_Method_Examples.m](https://github.com/danielrherber/optimal-control-direct-method-examples/blob/master/INSTALL_Direct_Method_Examples.m)) first?

I just tested the project code successfully on the following configurations that I have available:
- R2017b, Windows
- R2017a, Windows
- R2016b, Windows
- R2016a, Mac

The install script does fail on versions before R2014b because the function [websave](https://www.mathworks.com/help/matlab/ref/websave.html) was introduced in R2014b. However, if you are using a version older than R2014b, you can manually download the required files, and the project should run fine.

**Comment by danielrherber** [comment]
Issue should be fixed in commit 1d996c95605275798982591d47c6bd1578019081. See issue #3.
